apiVersion: v1
kind: Secret
metadata:
  name: release-name-postgresql-ha-pgpool
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-11.7.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: pgpool
type: Opaque
data:
  admin-password: dlJNZ2FqSFJwNw==
---
apiVersion: v1
kind: Secret
metadata:
  name: release-name-postgresql-ha-postgresql
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-11.7.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  password: TlVlZlNZZ3RORg==
  repmgr-password: ZmFHS0l0TXlhdA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-postgresql-ha-postgresql-hooks-scripts
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-11.7.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
data:
  pre-stop.sh: "#!/bin/bash\nset -o errexit\nset -o pipefail\nset -o nounset\n\n#\
    \ Debug section\nexec 3>&1\nexec 4>&2\n\n# Process input parameters\nMIN_DELAY_AFTER_PG_STOP_SECONDS=$1\n\
    \n# Load Libraries\n. /opt/bitnami/scripts/liblog.sh\n. /opt/bitnami/scripts/libpostgresql.sh\n\
    . /opt/bitnami/scripts/librepmgr.sh\n\n# Load PostgreSQL & repmgr environment\
    \ variables\n. /opt/bitnami/scripts/postgresql-env.sh\n\n# Auxiliary functions\n\
    is_new_primary_ready() {\n    return_value=1\n    currenty_primary_node=\"$(repmgr_get_primary_node)\"\
    \n    currenty_primary_host=\"$(echo $currenty_primary_node | awk '{print $1}')\"\
    \n\n    info \"$currenty_primary_host != $REPMGR_NODE_NETWORK_NAME\"\n    if [[\
    \ $(echo $currenty_primary_node | wc -w) -eq 2 ]] && [[ \"$currenty_primary_host\"\
    \ != \"$REPMGR_NODE_NETWORK_NAME\" ]]; then\n        info \"New primary detected,\
    \ leaving the cluster...\"\n        return_value=0\n    else\n        info \"\
    Waiting for a new primary to be available...\"\n    fi\n    return $return_value\n\
    }\n\nexport MODULE=\"pre-stop-hook\"\n\nif [[ \"${BITNAMI_DEBUG}\" == \"true\"\
    \ ]]; then\n    info \"Bash debug is on\"\nelse\n    info \"Bash debug is off\"\
    \n    exec 1>/dev/null\n    exec 2>/dev/null\nfi\n\npostgresql_enable_nss_wrapper\n\
    \n# Prepare env vars for managing roles\nreadarray -t primary_node < <(repmgr_get_upstream_node)\n\
    primary_host=\"${primary_node[0]}\"\n\n# Stop postgresql for graceful exit.\n\
    PG_STOP_TIME=$EPOCHSECONDS\npostgresql_stop\n\nif [[ -z \"$primary_host\" ]] ||\
    \ [[ \"$primary_host\" == \"$REPMGR_NODE_NETWORK_NAME\" ]]; then\n    info \"\
    Primary node need to wait for a new primary node before leaving the cluster\"\n\
    \    retry_while is_new_primary_ready 10 5\nelse\n    info \"Standby node doesn't\
    \ need to wait for a new primary switchover. Leaving the cluster\"\nfi\n\n# Make\
    \ sure pre-stop hook waits at least 25 seconds after stop of PG to make sure PGPOOL\
    \ detects node is down.\n# default terminationGracePeriodSeconds=30 seconds\n\
    PG_STOP_DURATION=$(($EPOCHSECONDS - $PG_STOP_TIME))\nif (( $PG_STOP_DURATION <\
    \ $MIN_DELAY_AFTER_PG_STOP_SECONDS )); then\n    WAIT_TO_PG_POOL_TIME=$(($MIN_DELAY_AFTER_PG_STOP_SECONDS\
    \ - $PG_STOP_DURATION)) \n    info \"PG stopped including primary switchover in\
    \ $PG_STOP_DURATION. Waiting additional $WAIT_TO_PG_POOL_TIME seconds for PG pool\"\
    \n    sleep $WAIT_TO_PG_POOL_TIME\nfi"
  readiness-probe.sh: "#!/bin/bash\nset -o errexit\nset -o pipefail\nset -o nounset\n\
    \n# Debug section\nexec 3>&1\nexec 4>&2\n\n# Load Libraries\n. /opt/bitnami/scripts/liblog.sh\n\
    . /opt/bitnami/scripts/libpostgresql.sh\n\n# Load PostgreSQL & repmgr environment\
    \ variables\n. /opt/bitnami/scripts/postgresql-env.sh\n\n# Process input parameters\n\
    MIN_DELAY_AFTER_POD_READY_FIRST_TIME=$1\nTMP_FIRST_READY_FILE_TS=\"/tmp/ts-first-ready.mark\"\
    \nTMP_DELAY_APPLIED_FILE=\"/tmp/delay-applied.mark\"\n\n\nDB_CHECK_RESULT=$(echo\
    \ \"SELECT 1\" | postgresql_execute \"$POSTGRESQL_DATABASE\" \"$POSTGRESQL_USERNAME\"\
    \ \"$POSTGRESQL_PASSWORD\" \"-h 127.0.0.1 -tA\" || \"command failed\")\nif [[\
    \ \"$DB_CHECK_RESULT\" == \"1\" ]]; then\n  if [[ ! -f \"$TMP_DELAY_APPLIED_FILE\"\
    \ ]]; then\n    # DB up, but initial readiness delay not applied\n    if [[ -f\
    \ \"$TMP_FIRST_READY_FILE_TS\" ]]; then\n      # calculate delay from the first\
    \ readiness success\n      FIRST_READY_TS=$(cat $TMP_FIRST_READY_FILE_TS)\n  \
    \    CURRENT_DELAY_SECONDS=$(($EPOCHSECONDS - $FIRST_READY_TS))\n      if (( $CURRENT_DELAY_SECONDS\
    \ > $MIN_DELAY_AFTER_POD_READY_FIRST_TIME )); then\n        # minimal delay of\
    \ the first readiness state passed - report success and mark delay as applied\n\
    \        touch \"$TMP_DELAY_APPLIED_FILE\"      \n      else\n        # minimal\
    \ delay of the first readiness state not reached yet - report failure\n      \
    \  return 1\n      fi\n    else\n      # first ever readiness test success - store\
    \ timestamp and report failure\n      echo $EPOCHSECONDS > $TMP_FIRST_READY_FILE_TS\n\
    \      return 1\n    fi\n  fi\nelse\n  # DB test failed - report failure\n  return\
    \ 1\nfi"
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-postgresql-ha-pgpool
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-11.7.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: pgpool
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
    nodePort: null
  selector:
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: pgpool
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-postgresql-ha-postgresql-headless
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-11.7.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: postgresql
    role: data
---
apiVersion: v1
kind: Service
metadata:
  name: release-name-postgresql-ha-postgresql
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-11.7.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    app.kubernetes.io/name: postgresql-ha
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: postgresql
    role: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-postgresql-ha-pgpool
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-11.7.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql-ha
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: pgpool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql-ha
        helm.sh/chart: postgresql-ha-11.7.4
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: pgpool
    spec:
      affinity:
        podAffinity: null
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: postgresql-ha
                  app.kubernetes.io/instance: release-name
                  app.kubernetes.io/component: pgpool
              topologyKey: kubernetes.io/hostname
            weight: 1
        nodeAffinity: null
      securityContext:
        fsGroup: 1001
      initContainers: null
      containers:
      - name: pgpool
        image: docker.io/bitnami/pgpool:4.4.3-debian-11-r1
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        env:
        - name: BITNAMI_DEBUG
          value: 'false'
        - name: PGPOOL_BACKEND_NODES
          value: 0:release-name-postgresql-ha-postgresql-0.release-name-postgresql-ha-postgresql-headless:5432,1:release-name-postgresql-ha-postgresql-1.release-name-postgresql-ha-postgresql-headless:5432,2:release-name-postgresql-ha-postgresql-2.release-name-postgresql-ha-postgresql-headless:5432,
        - name: PGPOOL_SR_CHECK_USER
          value: repmgr
        - name: PGPOOL_SR_CHECK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-postgresql-ha-postgresql
              key: repmgr-password
        - name: PGPOOL_SR_CHECK_DATABASE
          value: postgres
        - name: PGPOOL_ENABLE_LDAP
          value: 'no'
        - name: PGPOOL_POSTGRES_USERNAME
          value: postgres
        - name: PGPOOL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-postgresql-ha-postgresql
              key: password
        - name: PGPOOL_ADMIN_USERNAME
          value: admin
        - name: PGPOOL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-postgresql-ha-pgpool
              key: admin-password
        - name: PGPOOL_AUTHENTICATION_METHOD
          value: scram-sha-256
        - name: PGPOOL_ENABLE_LOAD_BALANCING
          value: 'yes'
        - name: PGPOOL_DISABLE_LOAD_BALANCE_ON_WRITE
          value: transaction
        - name: PGPOOL_ENABLE_LOG_CONNECTIONS
          value: 'no'
        - name: PGPOOL_ENABLE_LOG_HOSTNAME
          value: 'yes'
        - name: PGPOOL_ENABLE_LOG_PER_NODE_STATEMENT
          value: 'no'
        - name: PGPOOL_RESERVED_CONNECTIONS
          value: '1'
        - name: PGPOOL_CHILD_LIFE_TIME
          value: ''
        - name: PGPOOL_ENABLE_TLS
          value: 'no'
        - name: PGPOOL_HEALTH_CHECK_PSQL_TIMEOUT
          value: '6'
        envFrom: null
        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          exec:
            command:
            - /opt/bitnami/scripts/pgpool/healthcheck.sh
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          exec:
            command:
            - bash
            - -ec
            - PGPASSWORD=${PGPOOL_POSTGRES_PASSWORD} psql -U "postgres" -d "postgres"
              -h /opt/bitnami/pgpool/tmp -tA -c "SELECT 1" >/dev/null
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi
        volumeMounts: null
      volumes: null
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-postgresql-ha-postgresql
  namespace: default
  labels:
    app.kubernetes.io/name: postgresql-ha
    helm.sh/chart: postgresql-ha-11.7.4
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgresql
    role: data
spec:
  replicas: 3
  podManagementPolicy: Parallel
  serviceName: release-name-postgresql-ha-postgresql-headless
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql-ha
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: postgresql
      role: data
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql-ha
        helm.sh/chart: postgresql-ha-11.7.4
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: postgresql
        role: data
    spec:
      affinity:
        podAffinity: null
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: postgresql-ha
                  app.kubernetes.io/instance: release-name
                  app.kubernetes.io/component: postgresql
              topologyKey: kubernetes.io/hostname
            weight: 1
        nodeAffinity: null
      securityContext:
        fsGroup: 1001
      hostNetwork: false
      hostIPC: false
      initContainers: null
      containers:
      - name: postgresql
        image: docker.io/bitnami/postgresql-repmgr:15.3.0-debian-11-r6
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
        lifecycle:
          preStop:
            exec:
              command:
              - /pre-stop.sh
              - '25'
        env:
        - name: BITNAMI_DEBUG
          value: 'false'
        - name: POSTGRESQL_VOLUME_DIR
          value: /bitnami/postgresql
        - name: PGDATA
          value: /bitnami/postgresql/data
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-postgresql-ha-postgresql
              key: password
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRESQL_LOG_HOSTNAME
          value: 'true'
        - name: POSTGRESQL_LOG_CONNECTIONS
          value: 'false'
        - name: POSTGRESQL_LOG_DISCONNECTIONS
          value: 'false'
        - name: POSTGRESQL_PGAUDIT_LOG_CATALOG
          value: 'off'
        - name: POSTGRESQL_CLIENT_MIN_MESSAGES
          value: error
        - name: POSTGRESQL_SHARED_PRELOAD_LIBRARIES
          value: pgaudit, repmgr
        - name: POSTGRESQL_ENABLE_TLS
          value: 'no'
        - name: POSTGRESQL_PORT_NUMBER
          value: '5432'
        - name: REPMGR_PORT_NUMBER
          value: '5432'
        - name: REPMGR_PRIMARY_PORT
          value: '5432'
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REPMGR_UPGRADE_EXTENSION
          value: 'no'
        - name: REPMGR_PGHBA_TRUST_ALL
          value: 'no'
        - name: REPMGR_MOUNTED_CONF_DIR
          value: /bitnami/repmgr/conf
        - name: REPMGR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REPMGR_PARTNER_NODES
          value: release-name-postgresql-ha-postgresql-0.release-name-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local,release-name-postgresql-ha-postgresql-1.release-name-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local,release-name-postgresql-ha-postgresql-2.release-name-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local,
        - name: REPMGR_PRIMARY_HOST
          value: release-name-postgresql-ha-postgresql-0.release-name-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local
        - name: REPMGR_NODE_NAME
          value: $(MY_POD_NAME)
        - name: REPMGR_NODE_NETWORK_NAME
          value: $(MY_POD_NAME).release-name-postgresql-ha-postgresql-headless.$(REPMGR_NAMESPACE).svc.cluster.local
        - name: REPMGR_NODE_TYPE
          value: data
        - name: REPMGR_LOG_LEVEL
          value: NOTICE
        - name: REPMGR_CONNECT_TIMEOUT
          value: '5'
        - name: REPMGR_RECONNECT_ATTEMPTS
          value: '2'
        - name: REPMGR_RECONNECT_INTERVAL
          value: '3'
        - name: REPMGR_USERNAME
          value: repmgr
        - name: REPMGR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: release-name-postgresql-ha-postgresql
              key: repmgr-password
        - name: REPMGR_DATABASE
          value: repmgr
        - name: REPMGR_FENCE_OLD_PRIMARY
          value: 'no'
        - name: REPMGR_CHILD_NODES_CHECK_INTERVAL
          value: '5'
        - name: REPMGR_CHILD_NODES_CONNECTED_MIN_COUNT
          value: '1'
        - name: REPMGR_CHILD_NODES_DISCONNECT_TIMEOUT
          value: '30'
        envFrom: null
        ports:
        - name: postgresql
          containerPort: 5432
          protocol: TCP
        livenessProbe:
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          exec:
            command:
            - bash
            - -ec
            - PGPASSWORD=$POSTGRES_PASSWORD psql -w -U "postgres" -d "postgres" -h
              127.0.0.1 -p 5432 -c "SELECT 1"
        readinessProbe:
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          exec:
            command:
            - bash
            - -ec
            - PGPASSWORD=$POSTGRES_PASSWORD psql -w -U "postgres" -d "postgres" -h
              127.0.0.1 -p 5432 -c "SELECT 1"
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 128Mi
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
        - name: hooks-scripts
          mountPath: /pre-stop.sh
          subPath: pre-stop.sh
        - name: hooks-scripts
          mountPath: /readiness-probe.sh
          subPath: readiness-probe.sh
      volumes:
      - name: hooks-scripts
        configMap:
          name: release-name-postgresql-ha-postgresql-hooks-scripts
          defaultMode: 493
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
