apiVersion: v1
kind: Pod
...
spec:
  containers:
  - name: my-container

  resources:
    limits:
      memory: "64Mi"
      cpu: "250m"
    requests:
      memory: "32Mi"
      cpu: "100m"

  securityContext:
    # Root user
    runAsUser: 0

    # Not read-only filesystem
    readOnlyRootFilesystem: false

    # Allow privilege escalation
    allowPrivilegeEscalation: true

---
apiVersion: v1
kind: NetworkPolicy


