apiVersion: v2
appVersion: 3.55.0
description: Sonatype Nexus Repository Manager - Universal Binary repository
home: https://www.sonatype.com/nexus-repository-oss
icon: https://sonatype.github.io/helm3-charts/NexusRepo_Vertical.svg
keywords:
- artifacts
- dependency
- management
- sonatype
- nexus
- repository
- quickstart
- ci
- repository-manager
- nexus3
maintainers:
- email: support@sonatype.com
  name: Sonatype
name: nexus-repository-manager
sources:
- https://github.com/sonatype/nexus-public
type: application
version: 55.0.0
