name: Run checker tool

on:
  workflow_call:
    inputs:

      iteration:
        required: true
        type: string

      chart_folder:
        required: true
        type: string

      first_tool:
        type: string
      
      second_tool:
        type: string  


jobs:

  run_checkov_first:
    if: ${{ inputs.first_tool == 'checkov' }}
    uses: ./.github/workflows/run_checkov.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_checkov_second:
    if: ${{ inputs.second_tool == 'checkov' }}
    uses: ./.github/workflows/run_checkov.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_datree_first:
    if: ${{ inputs.first_tool == 'datree' }}
    uses: ./.github/workflows/run_datree.yaml      
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}
    secrets: inherit

  run_datree_second:
    if: ${{ inputs.second_tool == 'datree' }}
    uses: ./.github/workflows/run_datree.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}
    secrets: inherit

  run_kics_first:
    if: ${{ inputs.first_tool == 'kics' }}
    uses: ./.github/workflows/run_kics.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_kics_second:
    if: ${{ inputs.second_tool == 'kics' }}
    uses: ./.github/workflows/run_kics.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_kubelinter_first:
    if: ${{ inputs.first_tool == 'kubelinter' }}
    uses: ./.github/workflows/run_kubelinter.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_kubelinter_second:
    if: ${{ inputs.second_tool == 'kubelinter' }}
    uses: ./.github/workflows/run_kubelinter.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_kubeaudit_first:
    if: ${{ inputs.first_tool == 'kubeaudit' }}
    uses: ./.github/workflows/run_kubeaudit.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_kubeaudit_second:
    if: ${{ inputs.second_tool == 'kubeaudit' }}
    uses: ./.github/workflows/run_kubeaudit.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_kubescape_first:
    if: ${{ inputs.first_tool == 'kubescape' }}
    uses: ./.github/workflows/run_kubescape.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_kubescape_second:
    if: ${{ inputs.second_tool == 'kubescape' }}
    uses: ./.github/workflows/run_kubescape.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_terrascan_first:
    if: ${{ inputs.first_tool == 'terrascan' }}
    uses: ./.github/workflows/run_terrascan.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_terrascan_second:
    if: ${{ inputs.second_tool == 'terrascan' }}
    uses: ./.github/workflows/run_terrascan.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}

  run_sonarcloud_first:
    if: ${{ inputs.first_tool == 'sonarcloud' }}
    uses: ./.github/workflows/run_sonarcloud.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}
    secrets: inherit

  run_sonarcloud_second:
    if: ${{ inputs.second_tool == 'sonarcloud' }}
    uses: ./.github/workflows/run_sonarcloud.yaml
    with:
      iteration: ${{ inputs.iteration }}
      chart_folder: ${{ inputs.chart_folder }}
    secrets: inherit

